/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Запрос регистрации ТС
    /// </summary>
    [DataContract]
        public partial class TruckRegisterRequest :  IEquatable<TruckRegisterRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TruckRegisterRequest" /> class.
        /// </summary>
        /// <param name="depCode">Код клиента (required).</param>
        /// <param name="warehouseCode">Код склада (required).</param>
        /// <param name="truckID">Уникальный код перевозки (required).</param>
        /// <param name="type">Вид операции,значения Приход, Расход (required).</param>
        /// <param name="contragent">В случае прихода - наименование отправителя, в случае заказа – наименование получателя.</param>
        /// <param name="truckNumber">Номер ТС.</param>
        /// <param name="sealNumber">Номер пломбы.</param>
        /// <param name="truckModel">Марка ТС.</param>
        /// <param name="transCompany">Транспортная компания.</param>
        /// <param name="driverFIO">ФИО водителя.</param>
        /// <param name="driverPassport">Паспортные данные водителя.</param>
        /// <param name="driverPhone">Телефон водителя.</param>
        /// <param name="driverLicence">Номер водительского удостоверения.</param>
        /// <param name="estDate">Ожидаемые дата и время прибытия.</param>
        /// <param name="description">Примечание.</param>
        /// <param name="docCodes">Номера документов (required).</param>
        public TruckRegisterRequest()
        {            
        }
        
        /// <summary>
        /// Код клиента
        /// </summary>
        /// <value>Код клиента</value>
        [DataMember(Name="depCode", EmitDefaultValue=false)]
        public string DepCode { get; set; }

        /// <summary>
        /// Код склада
        /// </summary>
        /// <value>Код склада</value>
        [DataMember(Name="warehouseCode", EmitDefaultValue=false)]
        public string WarehouseCode { get; set; }

        /// <summary>
        /// Уникальный код перевозки
        /// </summary>
        /// <value>Уникальный код перевозки</value>
        [DataMember(Name="truckID", EmitDefaultValue=false)]
        public string TruckID { get; set; }

        /// <summary>
        /// Вид операции,значения Приход, Расход
        /// </summary>
        /// <value>Вид операции,значения Приход, Расход</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// В случае прихода - наименование отправителя, в случае заказа – наименование получателя
        /// </summary>
        /// <value>В случае прихода - наименование отправителя, в случае заказа – наименование получателя</value>
        [DataMember(Name="contragent", EmitDefaultValue=false)]
        public string Contragent { get; set; }

        /// <summary>
        /// Номер ТС
        /// </summary>
        /// <value>Номер ТС</value>
        [DataMember(Name="truckNumber", EmitDefaultValue=false)]
        public string TruckNumber { get; set; }

        /// <summary>
        /// Номер пломбы
        /// </summary>
        /// <value>Номер пломбы</value>
        [DataMember(Name="sealNumber", EmitDefaultValue=false)]
        public string SealNumber { get; set; }

        /// <summary>
        /// Марка ТС
        /// </summary>
        /// <value>Марка ТС</value>
        [DataMember(Name="truckModel", EmitDefaultValue=false)]
        public string TruckModel { get; set; }

        /// <summary>
        /// Транспортная компания
        /// </summary>
        /// <value>Транспортная компания</value>
        [DataMember(Name="transCompany", EmitDefaultValue=false)]
        public string TransCompany { get; set; }

        /// <summary>
        /// ФИО водителя
        /// </summary>
        /// <value>ФИО водителя</value>
        [DataMember(Name="driverFIO", EmitDefaultValue=false)]
        public string DriverFIO { get; set; }

        /// <summary>
        /// Паспортные данные водителя
        /// </summary>
        /// <value>Паспортные данные водителя</value>
        [DataMember(Name="driverPassport", EmitDefaultValue=false)]
        public string DriverPassport { get; set; }

        /// <summary>
        /// Телефон водителя
        /// </summary>
        /// <value>Телефон водителя</value>
        [DataMember(Name="driverPhone", EmitDefaultValue=false)]
        public string DriverPhone { get; set; }

        /// <summary>
        /// Номер водительского удостоверения
        /// </summary>
        /// <value>Номер водительского удостоверения</value>
        [DataMember(Name="driverLicence", EmitDefaultValue=false)]
        public string DriverLicence { get; set; }

        /// <summary>
        /// Ожидаемые дата и время прибытия
        /// </summary>
        /// <value>Ожидаемые дата и время прибытия</value>
        [DataMember(Name="estDate", EmitDefaultValue=false)]
        public DateTime? EstDate { get; set; }

        /// <summary>
        /// Примечание
        /// </summary>
        /// <value>Примечание</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Номера документов
        /// </summary>
        /// <value>Номера документов</value>
        [DataMember(Name="docCodes", EmitDefaultValue=false)]
        public List<string> DocCodes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TruckRegisterRequest {\n");
            sb.Append("  DepCode: ").Append(DepCode).Append("\n");
            sb.Append("  WarehouseCode: ").Append(WarehouseCode).Append("\n");
            sb.Append("  TruckID: ").Append(TruckID).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Contragent: ").Append(Contragent).Append("\n");
            sb.Append("  TruckNumber: ").Append(TruckNumber).Append("\n");
            sb.Append("  SealNumber: ").Append(SealNumber).Append("\n");
            sb.Append("  TruckModel: ").Append(TruckModel).Append("\n");
            sb.Append("  TransCompany: ").Append(TransCompany).Append("\n");
            sb.Append("  DriverFIO: ").Append(DriverFIO).Append("\n");
            sb.Append("  DriverPassport: ").Append(DriverPassport).Append("\n");
            sb.Append("  DriverPhone: ").Append(DriverPhone).Append("\n");
            sb.Append("  DriverLicence: ").Append(DriverLicence).Append("\n");
            sb.Append("  EstDate: ").Append(EstDate).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DocCodes: ").Append(DocCodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TruckRegisterRequest);
        }

        /// <summary>
        /// Returns true if TruckRegisterRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TruckRegisterRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TruckRegisterRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DepCode == input.DepCode ||
                    (this.DepCode != null &&
                    this.DepCode.Equals(input.DepCode))
                ) && 
                (
                    this.WarehouseCode == input.WarehouseCode ||
                    (this.WarehouseCode != null &&
                    this.WarehouseCode.Equals(input.WarehouseCode))
                ) && 
                (
                    this.TruckID == input.TruckID ||
                    (this.TruckID != null &&
                    this.TruckID.Equals(input.TruckID))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Contragent == input.Contragent ||
                    (this.Contragent != null &&
                    this.Contragent.Equals(input.Contragent))
                ) && 
                (
                    this.TruckNumber == input.TruckNumber ||
                    (this.TruckNumber != null &&
                    this.TruckNumber.Equals(input.TruckNumber))
                ) && 
                (
                    this.SealNumber == input.SealNumber ||
                    (this.SealNumber != null &&
                    this.SealNumber.Equals(input.SealNumber))
                ) && 
                (
                    this.TruckModel == input.TruckModel ||
                    (this.TruckModel != null &&
                    this.TruckModel.Equals(input.TruckModel))
                ) && 
                (
                    this.TransCompany == input.TransCompany ||
                    (this.TransCompany != null &&
                    this.TransCompany.Equals(input.TransCompany))
                ) && 
                (
                    this.DriverFIO == input.DriverFIO ||
                    (this.DriverFIO != null &&
                    this.DriverFIO.Equals(input.DriverFIO))
                ) && 
                (
                    this.DriverPassport == input.DriverPassport ||
                    (this.DriverPassport != null &&
                    this.DriverPassport.Equals(input.DriverPassport))
                ) && 
                (
                    this.DriverPhone == input.DriverPhone ||
                    (this.DriverPhone != null &&
                    this.DriverPhone.Equals(input.DriverPhone))
                ) && 
                (
                    this.DriverLicence == input.DriverLicence ||
                    (this.DriverLicence != null &&
                    this.DriverLicence.Equals(input.DriverLicence))
                ) && 
                (
                    this.EstDate == input.EstDate ||
                    (this.EstDate != null &&
                    this.EstDate.Equals(input.EstDate))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.DocCodes == input.DocCodes ||
                    this.DocCodes != null &&
                    input.DocCodes != null &&
                    this.DocCodes.SequenceEqual(input.DocCodes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DepCode != null)
                    hashCode = hashCode * 59 + this.DepCode.GetHashCode();
                if (this.WarehouseCode != null)
                    hashCode = hashCode * 59 + this.WarehouseCode.GetHashCode();
                if (this.TruckID != null)
                    hashCode = hashCode * 59 + this.TruckID.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Contragent != null)
                    hashCode = hashCode * 59 + this.Contragent.GetHashCode();
                if (this.TruckNumber != null)
                    hashCode = hashCode * 59 + this.TruckNumber.GetHashCode();
                if (this.SealNumber != null)
                    hashCode = hashCode * 59 + this.SealNumber.GetHashCode();
                if (this.TruckModel != null)
                    hashCode = hashCode * 59 + this.TruckModel.GetHashCode();
                if (this.TransCompany != null)
                    hashCode = hashCode * 59 + this.TransCompany.GetHashCode();
                if (this.DriverFIO != null)
                    hashCode = hashCode * 59 + this.DriverFIO.GetHashCode();
                if (this.DriverPassport != null)
                    hashCode = hashCode * 59 + this.DriverPassport.GetHashCode();
                if (this.DriverPhone != null)
                    hashCode = hashCode * 59 + this.DriverPhone.GetHashCode();
                if (this.DriverLicence != null)
                    hashCode = hashCode * 59 + this.DriverLicence.GetHashCode();
                if (this.EstDate != null)
                    hashCode = hashCode * 59 + this.EstDate.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.DocCodes != null)
                    hashCode = hashCode * 59 + this.DocCodes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
