/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// ReceiptStatusItemDTO
    /// </summary>
    [DataContract]
        public partial class ReceiptStatusItemDTO :  IEquatable<ReceiptStatusItemDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceiptStatusItemDTO" /> class.
        /// </summary>
        /// <param name="number">Номр строки.</param>
        /// <param name="prdCode">Артикул (required).</param>
        /// <param name="prdCodeExternal">Артикул клиентский.</param>
        /// <param name="qtyPlan">Количество план (required).</param>
        /// <param name="qtyFact">Количество факт (required).</param>
        /// <param name="quality">Качество. Если принят годный, поле пустое в противном случае код причины отбраковки (required).</param>
        /// <param name="expDate">Дата окончания срока годности.</param>
        /// <param name="lot">Номер принятой партии.</param>
        /// <param name="sscc">Номер контейнера.</param>
        public ReceiptStatusItemDTO(string number = default(string), string prdCode = default(string), string prdCodeExternal = default(string), int? qtyPlan = default(int?), int? qtyFact = default(int?), string quality = default(string), string expDate = default(string), string lot = default(string), string sscc = default(string))
        {
            // to ensure "prdCode" is required (not null)
            if (prdCode == null)
            {
                throw new InvalidDataException("prdCode is a required property for ReceiptStatusItemDTO and cannot be null");
            }
            else
            {
                this.PrdCode = prdCode;
            }
            // to ensure "qtyPlan" is required (not null)
            if (qtyPlan == null)
            {
                throw new InvalidDataException("qtyPlan is a required property for ReceiptStatusItemDTO and cannot be null");
            }
            else
            {
                this.QtyPlan = qtyPlan;
            }
            // to ensure "qtyFact" is required (not null)
            if (qtyFact == null)
            {
                throw new InvalidDataException("qtyFact is a required property for ReceiptStatusItemDTO and cannot be null");
            }
            else
            {
                this.QtyFact = qtyFact;
            }
            // to ensure "quality" is required (not null)
            if (quality == null)
            {
                throw new InvalidDataException("quality is a required property for ReceiptStatusItemDTO and cannot be null");
            }
            else
            {
                this.Quality = quality;
            }
            this.Number = number;
            this.PrdCodeExternal = prdCodeExternal;
            this.ExpDate = expDate;
            this.Lot = lot;
            this.Sscc = sscc;
        }
        
        /// <summary>
        /// Номр строки
        /// </summary>
        /// <value>Номр строки</value>
        [DataMember(Name="number", EmitDefaultValue=false)]
        public string Number { get; set; }

        /// <summary>
        /// Артикул
        /// </summary>
        /// <value>Артикул</value>
        [DataMember(Name="prdCode", EmitDefaultValue=false)]
        public string PrdCode { get; set; }

        /// <summary>
        /// Артикул клиентский
        /// </summary>
        /// <value>Артикул клиентский</value>
        [DataMember(Name="prdCodeExternal", EmitDefaultValue=false)]
        public string PrdCodeExternal { get; set; }

        /// <summary>
        /// Количество план
        /// </summary>
        /// <value>Количество план</value>
        [DataMember(Name="qtyPlan", EmitDefaultValue=false)]
        public int? QtyPlan { get; set; }

        /// <summary>
        /// Количество факт
        /// </summary>
        /// <value>Количество факт</value>
        [DataMember(Name="qtyFact", EmitDefaultValue=false)]
        public int? QtyFact { get; set; }

        /// <summary>
        /// Качество. Если принят годный, поле пустое в противном случае код причины отбраковки
        /// </summary>
        /// <value>Качество. Если принят годный, поле пустое в противном случае код причины отбраковки</value>
        [DataMember(Name="quality", EmitDefaultValue=false)]
        public string Quality { get; set; }

        /// <summary>
        /// Дата окончания срока годности
        /// </summary>
        /// <value>Дата окончания срока годности</value>
        [DataMember(Name="expDate", EmitDefaultValue=false)]
        public string ExpDate { get; set; }

        /// <summary>
        /// Номер принятой партии
        /// </summary>
        /// <value>Номер принятой партии</value>
        [DataMember(Name="lot", EmitDefaultValue=false)]
        public string Lot { get; set; }

        /// <summary>
        /// Номер контейнера
        /// </summary>
        /// <value>Номер контейнера</value>
        [DataMember(Name="sscc", EmitDefaultValue=false)]
        public string Sscc { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReceiptStatusItemDTO {\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  PrdCode: ").Append(PrdCode).Append("\n");
            sb.Append("  PrdCodeExternal: ").Append(PrdCodeExternal).Append("\n");
            sb.Append("  QtyPlan: ").Append(QtyPlan).Append("\n");
            sb.Append("  QtyFact: ").Append(QtyFact).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  ExpDate: ").Append(ExpDate).Append("\n");
            sb.Append("  Lot: ").Append(Lot).Append("\n");
            sb.Append("  Sscc: ").Append(Sscc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReceiptStatusItemDTO);
        }

        /// <summary>
        /// Returns true if ReceiptStatusItemDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceiptStatusItemDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceiptStatusItemDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Number == input.Number ||
                    (this.Number != null &&
                    this.Number.Equals(input.Number))
                ) && 
                (
                    this.PrdCode == input.PrdCode ||
                    (this.PrdCode != null &&
                    this.PrdCode.Equals(input.PrdCode))
                ) && 
                (
                    this.PrdCodeExternal == input.PrdCodeExternal ||
                    (this.PrdCodeExternal != null &&
                    this.PrdCodeExternal.Equals(input.PrdCodeExternal))
                ) && 
                (
                    this.QtyPlan == input.QtyPlan ||
                    (this.QtyPlan != null &&
                    this.QtyPlan.Equals(input.QtyPlan))
                ) && 
                (
                    this.QtyFact == input.QtyFact ||
                    (this.QtyFact != null &&
                    this.QtyFact.Equals(input.QtyFact))
                ) && 
                (
                    this.Quality == input.Quality ||
                    (this.Quality != null &&
                    this.Quality.Equals(input.Quality))
                ) && 
                (
                    this.ExpDate == input.ExpDate ||
                    (this.ExpDate != null &&
                    this.ExpDate.Equals(input.ExpDate))
                ) && 
                (
                    this.Lot == input.Lot ||
                    (this.Lot != null &&
                    this.Lot.Equals(input.Lot))
                ) && 
                (
                    this.Sscc == input.Sscc ||
                    (this.Sscc != null &&
                    this.Sscc.Equals(input.Sscc))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Number != null)
                    hashCode = hashCode * 59 + this.Number.GetHashCode();
                if (this.PrdCode != null)
                    hashCode = hashCode * 59 + this.PrdCode.GetHashCode();
                if (this.PrdCodeExternal != null)
                    hashCode = hashCode * 59 + this.PrdCodeExternal.GetHashCode();
                if (this.QtyPlan != null)
                    hashCode = hashCode * 59 + this.QtyPlan.GetHashCode();
                if (this.QtyFact != null)
                    hashCode = hashCode * 59 + this.QtyFact.GetHashCode();
                if (this.Quality != null)
                    hashCode = hashCode * 59 + this.Quality.GetHashCode();
                if (this.ExpDate != null)
                    hashCode = hashCode * 59 + this.ExpDate.GetHashCode();
                if (this.Lot != null)
                    hashCode = hashCode * 59 + this.Lot.GetHashCode();
                if (this.Sscc != null)
                    hashCode = hashCode * 59 + this.Sscc.GetHashCode();
                return hashCode;
            }
        }
    }
}
