/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Класс поставки маркировки
    /// </summary>
    [DataContract]
        public partial class ReceiptSerialNumbersRequest :  IEquatable<ReceiptSerialNumbersRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceiptSerialNumbersRequest" /> class.
        /// </summary>
        /// <param name="code">Код (required).</param>
        /// <param name="depCode">Код клиента (required).</param>
        /// <param name="warehouseCode">Код склада (required).</param>
        /// <param name="items">Строки поставки (required).</param>
        public ReceiptSerialNumbersRequest(string code = default(string), string depCode = default(string), string warehouseCode = default(string), List<ReceiptSerialNumbersItemDTO> items = default(List<ReceiptSerialNumbersItemDTO>))
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new InvalidDataException("code is a required property for ReceiptSerialNumbersRequest and cannot be null");
            }
            else
            {
                this.Code = code;
            }
            // to ensure "depCode" is required (not null)
            if (depCode == null)
            {
                throw new InvalidDataException("depCode is a required property for ReceiptSerialNumbersRequest and cannot be null");
            }
            else
            {
                this.DepCode = depCode;
            }
            // to ensure "warehouseCode" is required (not null)
            if (warehouseCode == null)
            {
                throw new InvalidDataException("warehouseCode is a required property for ReceiptSerialNumbersRequest and cannot be null");
            }
            else
            {
                this.WarehouseCode = warehouseCode;
            }
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new InvalidDataException("items is a required property for ReceiptSerialNumbersRequest and cannot be null");
            }
            else
            {
                this.Items = items;
            }
        }
        
        /// <summary>
        /// Код
        /// </summary>
        /// <value>Код</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Код клиента
        /// </summary>
        /// <value>Код клиента</value>
        [DataMember(Name="depCode", EmitDefaultValue=false)]
        public string DepCode { get; set; }

        /// <summary>
        /// Код склада
        /// </summary>
        /// <value>Код склада</value>
        [DataMember(Name="warehouseCode", EmitDefaultValue=false)]
        public string WarehouseCode { get; set; }

        /// <summary>
        /// Строки поставки
        /// </summary>
        /// <value>Строки поставки</value>
        [DataMember(Name="items", EmitDefaultValue=false)]
        public List<ReceiptSerialNumbersItemDTO> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReceiptSerialNumbersRequest {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  DepCode: ").Append(DepCode).Append("\n");
            sb.Append("  WarehouseCode: ").Append(WarehouseCode).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReceiptSerialNumbersRequest);
        }

        /// <summary>
        /// Returns true if ReceiptSerialNumbersRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceiptSerialNumbersRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceiptSerialNumbersRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.DepCode == input.DepCode ||
                    (this.DepCode != null &&
                    this.DepCode.Equals(input.DepCode))
                ) && 
                (
                    this.WarehouseCode == input.WarehouseCode ||
                    (this.WarehouseCode != null &&
                    this.WarehouseCode.Equals(input.WarehouseCode))
                ) && 
                (
                    this.Items == input.Items ||
                    this.Items != null &&
                    input.Items != null &&
                    this.Items.SequenceEqual(input.Items)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.DepCode != null)
                    hashCode = hashCode * 59 + this.DepCode.GetHashCode();
                if (this.WarehouseCode != null)
                    hashCode = hashCode * 59 + this.WarehouseCode.GetHashCode();
                if (this.Items != null)
                    hashCode = hashCode * 59 + this.Items.GetHashCode();
                return hashCode;
            }
        }
    }
}
