/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Строка поставки
    /// </summary>
    [DataContract]
        public partial class ReceiptItemDTO :  IEquatable<ReceiptItemDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceiptItemDTO" /> class.
        /// </summary>
        /// <param name="number">Номер строки.</param>
        /// <param name="prdCode">Артикул (required).</param>
        /// <param name="prdCodeExternal">Артикул клиентский.</param>
        /// <param name="prdName">Наименование товара (required).</param>
        /// <param name="prdShortName">Краткое наименование товара.</param>
        /// <param name="prdBrand">Торговая марка.</param>
        /// <param name="prdType">Тип товара.</param>
        /// <param name="prdCountry">Страна происхождения.</param>
        /// <param name="qty">Количество (required).</param>
        /// <param name="isExpDate">Признак учета годности (required).</param>
        /// <param name="expDate">Срок годности.</param>
        /// <param name="isLot">Признак учета партий (required).</param>
        /// <param name="lot">Партия.</param>
        /// <param name="sscc">Код контейнера.</param>
        /// <param name="isContractPrice">Является ли цена по контракту (required).</param>
        /// <param name="price">Цена в рублях (required).</param>
        /// <param name="snType">Тип серийного номера (required) (default to &quot;нет&quot;).</param>
        /// <param name="length">Глубина, PCE CM.</param>
        /// <param name="width">Ширина PCE, CM.</param>
        /// <param name="height">Высота PCE, CM.</param>
        /// <param name="weight">Вес Нетто PCE, kg.</param>
        /// <param name="itemInBox">ШТ в упаковке(коробке).</param>
        /// <param name="manufacturer">Изготовитель.</param>
        /// <param name="factory">Производитель.</param>
        /// <param name="instruction">Инструкция, Тех регламент.</param>
        /// <param name="importer">Импортер.</param>
        /// <param name="gender">Пол.</param>
        /// <param name="seller">Продавец.</param>
        /// <param name="color">Цвет.</param>
        /// <param name="size">Размер.</param>
        /// <param name="structure">Состав.</param>
        /// <param name="isNeedCheck">Требуется ли дополнительная проверка товара.</param>
        /// <param name="prdCategory">Категория товара.</param>
        /// <param name="prdGroup">Группа товара.</param>
        /// <param name="codeOnboxe">Код на коробке.</param>
        /// <param name="addInfo">Дополнительная информация по товару.</param>
        /// <param name="mboxWidth">Ширина мастер короба.</param>
        /// <param name="mboxDepth">Глубина мастер короба.</param>
        /// <param name="mboxHeight">Высота мастер короба.</param>
        /// <param name="mboxWeight">Вес мастер короба в кг.</param>
        /// <param name="boxWidth">Ширина короба.</param>
        /// <param name="boxDepth">Глубина короба.</param>
        /// <param name="boxHeight">Высота короба.</param>
        /// <param name="boxWeight">Вес короба.</param>
        /// <param name="itemInMbox">Количество БЕИ в мастер коробе.</param>
        /// <param name="p18">Количество БЕИ на паллете высотой 1,8м.</param>
        /// <param name="p22">Количество БЕИ на паллете высотой 2,2м.</param>
        /// <param name="barcodes">Штрихкоды (required).</param>
        /// <param name="aggregationCodes">Агрегированные коды маркировки.</param>
        /// <param name="serialNumbers">Маркировка.</param>
        public ReceiptItemDTO()
        {
        }
        
        /// <summary>
        /// Номер строки
        /// </summary>
        /// <value>Номер строки</value>
        [DataMember(Name="number", EmitDefaultValue=false)]
        public string Number { get; set; }

        /// <summary>
        /// Артикул
        /// </summary>
        /// <value>Артикул</value>
        [DataMember(Name="prdCode", EmitDefaultValue=false)]
        public string PrdCode { get; set; }

        /// <summary>
        /// Артикул клиентский
        /// </summary>
        /// <value>Артикул клиентский</value>
        [DataMember(Name="prdCodeExternal", EmitDefaultValue=false)]
        public string PrdCodeExternal { get; set; }

        /// <summary>
        /// Наименование товара
        /// </summary>
        /// <value>Наименование товара</value>
        [DataMember(Name="prdName", EmitDefaultValue=false)]
        public string PrdName { get; set; }

        /// <summary>
        /// Краткое наименование товара
        /// </summary>
        /// <value>Краткое наименование товара</value>
        [DataMember(Name="prdShortName", EmitDefaultValue=false)]
        public string PrdShortName { get; set; }

        /// <summary>
        /// Торговая марка
        /// </summary>
        /// <value>Торговая марка</value>
        [DataMember(Name="prdBrand", EmitDefaultValue=false)]
        public string PrdBrand { get; set; }

        /// <summary>
        /// Тип товара
        /// </summary>
        /// <value>Тип товара</value>
        [DataMember(Name="prdType", EmitDefaultValue=false)]
        public string PrdType { get; set; }

        /// <summary>
        /// Страна происхождения
        /// </summary>
        /// <value>Страна происхождения</value>
        [DataMember(Name="prdCountry", EmitDefaultValue=false)]
        public string PrdCountry { get; set; }

        /// <summary>
        /// Количество
        /// </summary>
        /// <value>Количество</value>
        [DataMember(Name="qty", EmitDefaultValue=false)]
        public int? Qty { get; set; }

        /// <summary>
        /// Признак учета годности
        /// </summary>
        /// <value>Признак учета годности</value>
        [DataMember(Name="isExpDate", EmitDefaultValue=false)]
        public bool? IsExpDate { get; set; }

        /// <summary>
        /// Срок годности
        /// </summary>
        /// <value>Срок годности</value>
        [DataMember(Name="expDate", EmitDefaultValue=false)]
        public DateTime? ExpDate { get; set; }

        /// <summary>
        /// Признак учета партий
        /// </summary>
        /// <value>Признак учета партий</value>
        [DataMember(Name="isLot", EmitDefaultValue=false)]
        public bool? IsLot { get; set; }

        /// <summary>
        /// Партия
        /// </summary>
        /// <value>Партия</value>
        [DataMember(Name="lot", EmitDefaultValue=false)]
        public string Lot { get; set; }

        /// <summary>
        /// Код контейнера
        /// </summary>
        /// <value>Код контейнера</value>
        [DataMember(Name="sscc", EmitDefaultValue=false)]
        public string Sscc { get; set; }

        /// <summary>
        /// Является ли цена по контракту
        /// </summary>
        /// <value>Является ли цена по контракту</value>
        [DataMember(Name="isContractPrice", EmitDefaultValue=false)]
        public bool? IsContractPrice { get; set; }

        /// <summary>
        /// Цена в рублях
        /// </summary>
        /// <value>Цена в рублях</value>
        [DataMember(Name="price", EmitDefaultValue=false)]
        public float? Price { get; set; }

        /// <summary>
        /// Тип серийного номера
        /// </summary>
        /// <value>Тип серийного номера</value>
        [DataMember(Name="snType", EmitDefaultValue=false)]
        public string SnType { get; set; }

        /// <summary>
        /// Глубина, PCE CM
        /// </summary>
        /// <value>Глубина, PCE CM</value>
        [DataMember(Name="length", EmitDefaultValue=false)]
        public float? Length { get; set; }

        /// <summary>
        /// Ширина PCE, CM
        /// </summary>
        /// <value>Ширина PCE, CM</value>
        [DataMember(Name="width", EmitDefaultValue=false)]
        public float? Width { get; set; }

        /// <summary>
        /// Высота PCE, CM
        /// </summary>
        /// <value>Высота PCE, CM</value>
        [DataMember(Name="height", EmitDefaultValue=false)]
        public float? Height { get; set; }

        /// <summary>
        /// Вес Нетто PCE, kg
        /// </summary>
        /// <value>Вес Нетто PCE, kg</value>
        [DataMember(Name="weight", EmitDefaultValue=false)]
        public float? Weight { get; set; }

        /// <summary>
        /// ШТ в упаковке(коробке)
        /// </summary>
        /// <value>ШТ в упаковке(коробке)</value>
        [DataMember(Name="itemInBox", EmitDefaultValue=false)]
        public int? ItemInBox { get; set; }

        /// <summary>
        /// Изготовитель
        /// </summary>
        /// <value>Изготовитель</value>
        [DataMember(Name="manufacturer", EmitDefaultValue=false)]
        public string Manufacturer { get; set; }

        /// <summary>
        /// Производитель
        /// </summary>
        /// <value>Производитель</value>
        [DataMember(Name="factory", EmitDefaultValue=false)]
        public string Factory { get; set; }

        /// <summary>
        /// Инструкция, Тех регламент
        /// </summary>
        /// <value>Инструкция, Тех регламент</value>
        [DataMember(Name="instruction", EmitDefaultValue=false)]
        public string Instruction { get; set; }

        /// <summary>
        /// Импортер
        /// </summary>
        /// <value>Импортер</value>
        [DataMember(Name="importer", EmitDefaultValue=false)]
        public string Importer { get; set; }

        /// <summary>
        /// Пол
        /// </summary>
        /// <value>Пол</value>
        [DataMember(Name="gender", EmitDefaultValue=false)]
        public string Gender { get; set; }

        /// <summary>
        /// Продавец
        /// </summary>
        /// <value>Продавец</value>
        [DataMember(Name="seller", EmitDefaultValue=false)]
        public string Seller { get; set; }

        /// <summary>
        /// Цвет
        /// </summary>
        /// <value>Цвет</value>
        [DataMember(Name="color", EmitDefaultValue=false)]
        public string Color { get; set; }

        /// <summary>
        /// Размер
        /// </summary>
        /// <value>Размер</value>
        [DataMember(Name="size", EmitDefaultValue=false)]
        public string Size { get; set; }

        /// <summary>
        /// Состав
        /// </summary>
        /// <value>Состав</value>
        [DataMember(Name="structure", EmitDefaultValue=false)]
        public string Structure { get; set; }

        /// <summary>
        /// Требуется ли дополнительная проверка товара
        /// </summary>
        /// <value>Требуется ли дополнительная проверка товара</value>
        [DataMember(Name="isNeedCheck", EmitDefaultValue=false)]
        public bool? IsNeedCheck { get; set; }

        /// <summary>
        /// Категория товара
        /// </summary>
        /// <value>Категория товара</value>
        [DataMember(Name="prdCategory", EmitDefaultValue=false)]
        public string PrdCategory { get; set; }

        /// <summary>
        /// Группа товара
        /// </summary>
        /// <value>Группа товара</value>
        [DataMember(Name="prdGroup", EmitDefaultValue=false)]
        public string PrdGroup { get; set; }

        /// <summary>
        /// Код на коробке
        /// </summary>
        /// <value>Код на коробке</value>
        [DataMember(Name="codeOnboxe", EmitDefaultValue=false)]
        public string CodeOnboxe { get; set; }

        /// <summary>
        /// Дополнительная информация по товару
        /// </summary>
        /// <value>Дополнительная информация по товару</value>
        [DataMember(Name="addInfo", EmitDefaultValue=false)]
        public string AddInfo { get; set; }

        /// <summary>
        /// Ширина мастер короба
        /// </summary>
        /// <value>Ширина мастер короба</value>
        [DataMember(Name="mboxWidth", EmitDefaultValue=false)]
        public float? MboxWidth { get; set; }

        /// <summary>
        /// Глубина мастер короба
        /// </summary>
        /// <value>Глубина мастер короба</value>
        [DataMember(Name="mboxDepth", EmitDefaultValue=false)]
        public float? MboxDepth { get; set; }

        /// <summary>
        /// Высота мастер короба
        /// </summary>
        /// <value>Высота мастер короба</value>
        [DataMember(Name="mboxHeight", EmitDefaultValue=false)]
        public float? MboxHeight { get; set; }

        /// <summary>
        /// Вес мастер короба в кг
        /// </summary>
        /// <value>Вес мастер короба в кг</value>
        [DataMember(Name="mboxWeight", EmitDefaultValue=false)]
        public float? MboxWeight { get; set; }

        /// <summary>
        /// Ширина короба
        /// </summary>
        /// <value>Ширина короба</value>
        [DataMember(Name="boxWidth", EmitDefaultValue=false)]
        public float? BoxWidth { get; set; }

        /// <summary>
        /// Глубина короба
        /// </summary>
        /// <value>Глубина короба</value>
        [DataMember(Name="boxDepth", EmitDefaultValue=false)]
        public float? BoxDepth { get; set; }

        /// <summary>
        /// Высота короба
        /// </summary>
        /// <value>Высота короба</value>
        [DataMember(Name="boxHeight", EmitDefaultValue=false)]
        public float? BoxHeight { get; set; }

        /// <summary>
        /// Вес короба
        /// </summary>
        /// <value>Вес короба</value>
        [DataMember(Name="boxWeight", EmitDefaultValue=false)]
        public float? BoxWeight { get; set; }

        /// <summary>
        /// Количество БЕИ в мастер коробе
        /// </summary>
        /// <value>Количество БЕИ в мастер коробе</value>
        [DataMember(Name="itemInMbox", EmitDefaultValue=false)]
        public int? ItemInMbox { get; set; }

        /// <summary>
        /// Количество БЕИ на паллете высотой 1,8м
        /// </summary>
        /// <value>Количество БЕИ на паллете высотой 1,8м</value>
        [DataMember(Name="p18", EmitDefaultValue=false)]
        public int? P18 { get; set; }

        /// <summary>
        /// Количество БЕИ на паллете высотой 2,2м
        /// </summary>
        /// <value>Количество БЕИ на паллете высотой 2,2м</value>
        [DataMember(Name="p22", EmitDefaultValue=false)]
        public int? P22 { get; set; }

        /// <summary>
        /// Штрихкоды
        /// </summary>
        /// <value>Штрихкоды</value>
        [DataMember(Name="barcodes", EmitDefaultValue=false)]
        public List<string> Barcodes { get; set; }

        /// <summary>
        /// Агрегированные коды маркировки
        /// </summary>
        /// <value>Агрегированные коды маркировки</value>
        [DataMember(Name="aggregationCodes", EmitDefaultValue=false)]
        public List<ReceiptAggregationCodesDTO> AggregationCodes { get; set; }

        /// <summary>
        /// Маркировка
        /// </summary>
        /// <value>Маркировка</value>
        [DataMember(Name="serialNumbers", EmitDefaultValue=false)]
        public List<string> SerialNumbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReceiptItemDTO {\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  PrdCode: ").Append(PrdCode).Append("\n");
            sb.Append("  PrdCodeExternal: ").Append(PrdCodeExternal).Append("\n");
            sb.Append("  PrdName: ").Append(PrdName).Append("\n");
            sb.Append("  PrdShortName: ").Append(PrdShortName).Append("\n");
            sb.Append("  PrdBrand: ").Append(PrdBrand).Append("\n");
            sb.Append("  PrdType: ").Append(PrdType).Append("\n");
            sb.Append("  PrdCountry: ").Append(PrdCountry).Append("\n");
            sb.Append("  Qty: ").Append(Qty).Append("\n");
            sb.Append("  IsExpDate: ").Append(IsExpDate).Append("\n");
            sb.Append("  ExpDate: ").Append(ExpDate).Append("\n");
            sb.Append("  IsLot: ").Append(IsLot).Append("\n");
            sb.Append("  Lot: ").Append(Lot).Append("\n");
            sb.Append("  Sscc: ").Append(Sscc).Append("\n");
            sb.Append("  IsContractPrice: ").Append(IsContractPrice).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  SnType: ").Append(SnType).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  ItemInBox: ").Append(ItemInBox).Append("\n");
            sb.Append("  Manufacturer: ").Append(Manufacturer).Append("\n");
            sb.Append("  Factory: ").Append(Factory).Append("\n");
            sb.Append("  Instruction: ").Append(Instruction).Append("\n");
            sb.Append("  Importer: ").Append(Importer).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  Seller: ").Append(Seller).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Structure: ").Append(Structure).Append("\n");
            sb.Append("  IsNeedCheck: ").Append(IsNeedCheck).Append("\n");
            sb.Append("  PrdCategory: ").Append(PrdCategory).Append("\n");
            sb.Append("  PrdGroup: ").Append(PrdGroup).Append("\n");
            sb.Append("  CodeOnboxe: ").Append(CodeOnboxe).Append("\n");
            sb.Append("  AddInfo: ").Append(AddInfo).Append("\n");
            sb.Append("  MboxWidth: ").Append(MboxWidth).Append("\n");
            sb.Append("  MboxDepth: ").Append(MboxDepth).Append("\n");
            sb.Append("  MboxHeight: ").Append(MboxHeight).Append("\n");
            sb.Append("  MboxWeight: ").Append(MboxWeight).Append("\n");
            sb.Append("  BoxWidth: ").Append(BoxWidth).Append("\n");
            sb.Append("  BoxDepth: ").Append(BoxDepth).Append("\n");
            sb.Append("  BoxHeight: ").Append(BoxHeight).Append("\n");
            sb.Append("  BoxWeight: ").Append(BoxWeight).Append("\n");
            sb.Append("  ItemInMbox: ").Append(ItemInMbox).Append("\n");
            sb.Append("  P18: ").Append(P18).Append("\n");
            sb.Append("  P22: ").Append(P22).Append("\n");
            sb.Append("  Barcodes: ").Append(Barcodes).Append("\n");
            sb.Append("  AggregationCodes: ").Append(AggregationCodes).Append("\n");
            sb.Append("  SerialNumbers: ").Append(SerialNumbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReceiptItemDTO);
        }

        /// <summary>
        /// Returns true if ReceiptItemDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceiptItemDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceiptItemDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Number == input.Number ||
                    (this.Number != null &&
                    this.Number.Equals(input.Number))
                ) && 
                (
                    this.PrdCode == input.PrdCode ||
                    (this.PrdCode != null &&
                    this.PrdCode.Equals(input.PrdCode))
                ) && 
                (
                    this.PrdCodeExternal == input.PrdCodeExternal ||
                    (this.PrdCodeExternal != null &&
                    this.PrdCodeExternal.Equals(input.PrdCodeExternal))
                ) && 
                (
                    this.PrdName == input.PrdName ||
                    (this.PrdName != null &&
                    this.PrdName.Equals(input.PrdName))
                ) && 
                (
                    this.PrdShortName == input.PrdShortName ||
                    (this.PrdShortName != null &&
                    this.PrdShortName.Equals(input.PrdShortName))
                ) && 
                (
                    this.PrdBrand == input.PrdBrand ||
                    (this.PrdBrand != null &&
                    this.PrdBrand.Equals(input.PrdBrand))
                ) && 
                (
                    this.PrdType == input.PrdType ||
                    (this.PrdType != null &&
                    this.PrdType.Equals(input.PrdType))
                ) && 
                (
                    this.PrdCountry == input.PrdCountry ||
                    (this.PrdCountry != null &&
                    this.PrdCountry.Equals(input.PrdCountry))
                ) && 
                (
                    this.Qty == input.Qty ||
                    (this.Qty != null &&
                    this.Qty.Equals(input.Qty))
                ) && 
                (
                    this.IsExpDate == input.IsExpDate ||
                    (this.IsExpDate != null &&
                    this.IsExpDate.Equals(input.IsExpDate))
                ) && 
                (
                    this.ExpDate == input.ExpDate ||
                    (this.ExpDate != null &&
                    this.ExpDate.Equals(input.ExpDate))
                ) && 
                (
                    this.IsLot == input.IsLot ||
                    (this.IsLot != null &&
                    this.IsLot.Equals(input.IsLot))
                ) && 
                (
                    this.Lot == input.Lot ||
                    (this.Lot != null &&
                    this.Lot.Equals(input.Lot))
                ) && 
                (
                    this.Sscc == input.Sscc ||
                    (this.Sscc != null &&
                    this.Sscc.Equals(input.Sscc))
                ) && 
                (
                    this.IsContractPrice == input.IsContractPrice ||
                    (this.IsContractPrice != null &&
                    this.IsContractPrice.Equals(input.IsContractPrice))
                ) && 
                (
                    this.Price == input.Price ||
                    (this.Price != null &&
                    this.Price.Equals(input.Price))
                ) && 
                (
                    this.SnType == input.SnType ||
                    (this.SnType != null &&
                    this.SnType.Equals(input.SnType))
                ) && 
                (
                    this.Length == input.Length ||
                    (this.Length != null &&
                    this.Length.Equals(input.Length))
                ) && 
                (
                    this.Width == input.Width ||
                    (this.Width != null &&
                    this.Width.Equals(input.Width))
                ) && 
                (
                    this.Height == input.Height ||
                    (this.Height != null &&
                    this.Height.Equals(input.Height))
                ) && 
                (
                    this.Weight == input.Weight ||
                    (this.Weight != null &&
                    this.Weight.Equals(input.Weight))
                ) && 
                (
                    this.ItemInBox == input.ItemInBox ||
                    (this.ItemInBox != null &&
                    this.ItemInBox.Equals(input.ItemInBox))
                ) && 
                (
                    this.Manufacturer == input.Manufacturer ||
                    (this.Manufacturer != null &&
                    this.Manufacturer.Equals(input.Manufacturer))
                ) && 
                (
                    this.Factory == input.Factory ||
                    (this.Factory != null &&
                    this.Factory.Equals(input.Factory))
                ) && 
                (
                    this.Instruction == input.Instruction ||
                    (this.Instruction != null &&
                    this.Instruction.Equals(input.Instruction))
                ) && 
                (
                    this.Importer == input.Importer ||
                    (this.Importer != null &&
                    this.Importer.Equals(input.Importer))
                ) && 
                (
                    this.Gender == input.Gender ||
                    (this.Gender != null &&
                    this.Gender.Equals(input.Gender))
                ) && 
                (
                    this.Seller == input.Seller ||
                    (this.Seller != null &&
                    this.Seller.Equals(input.Seller))
                ) && 
                (
                    this.Color == input.Color ||
                    (this.Color != null &&
                    this.Color.Equals(input.Color))
                ) && 
                (
                    this.Size == input.Size ||
                    (this.Size != null &&
                    this.Size.Equals(input.Size))
                ) && 
                (
                    this.Structure == input.Structure ||
                    (this.Structure != null &&
                    this.Structure.Equals(input.Structure))
                ) && 
                (
                    this.IsNeedCheck == input.IsNeedCheck ||
                    (this.IsNeedCheck != null &&
                    this.IsNeedCheck.Equals(input.IsNeedCheck))
                ) && 
                (
                    this.PrdCategory == input.PrdCategory ||
                    (this.PrdCategory != null &&
                    this.PrdCategory.Equals(input.PrdCategory))
                ) && 
                (
                    this.PrdGroup == input.PrdGroup ||
                    (this.PrdGroup != null &&
                    this.PrdGroup.Equals(input.PrdGroup))
                ) && 
                (
                    this.CodeOnboxe == input.CodeOnboxe ||
                    (this.CodeOnboxe != null &&
                    this.CodeOnboxe.Equals(input.CodeOnboxe))
                ) && 
                (
                    this.AddInfo == input.AddInfo ||
                    (this.AddInfo != null &&
                    this.AddInfo.Equals(input.AddInfo))
                ) && 
                (
                    this.MboxWidth == input.MboxWidth ||
                    (this.MboxWidth != null &&
                    this.MboxWidth.Equals(input.MboxWidth))
                ) && 
                (
                    this.MboxDepth == input.MboxDepth ||
                    (this.MboxDepth != null &&
                    this.MboxDepth.Equals(input.MboxDepth))
                ) && 
                (
                    this.MboxHeight == input.MboxHeight ||
                    (this.MboxHeight != null &&
                    this.MboxHeight.Equals(input.MboxHeight))
                ) && 
                (
                    this.MboxWeight == input.MboxWeight ||
                    (this.MboxWeight != null &&
                    this.MboxWeight.Equals(input.MboxWeight))
                ) && 
                (
                    this.BoxWidth == input.BoxWidth ||
                    (this.BoxWidth != null &&
                    this.BoxWidth.Equals(input.BoxWidth))
                ) && 
                (
                    this.BoxDepth == input.BoxDepth ||
                    (this.BoxDepth != null &&
                    this.BoxDepth.Equals(input.BoxDepth))
                ) && 
                (
                    this.BoxHeight == input.BoxHeight ||
                    (this.BoxHeight != null &&
                    this.BoxHeight.Equals(input.BoxHeight))
                ) && 
                (
                    this.BoxWeight == input.BoxWeight ||
                    (this.BoxWeight != null &&
                    this.BoxWeight.Equals(input.BoxWeight))
                ) && 
                (
                    this.ItemInMbox == input.ItemInMbox ||
                    (this.ItemInMbox != null &&
                    this.ItemInMbox.Equals(input.ItemInMbox))
                ) && 
                (
                    this.P18 == input.P18 ||
                    (this.P18 != null &&
                    this.P18.Equals(input.P18))
                ) && 
                (
                    this.P22 == input.P22 ||
                    (this.P22 != null &&
                    this.P22.Equals(input.P22))
                ) && 
                (
                    this.Barcodes == input.Barcodes ||
                    this.Barcodes != null &&
                    input.Barcodes != null &&
                    this.Barcodes.SequenceEqual(input.Barcodes)
                ) && 
                (
                    this.AggregationCodes == input.AggregationCodes ||
                    this.AggregationCodes != null &&
                    input.AggregationCodes != null &&
                    this.AggregationCodes.SequenceEqual(input.AggregationCodes)
                ) && 
                (
                    this.SerialNumbers == input.SerialNumbers ||
                    this.SerialNumbers != null &&
                    input.SerialNumbers != null &&
                    this.SerialNumbers.SequenceEqual(input.SerialNumbers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Number != null)
                    hashCode = hashCode * 59 + this.Number.GetHashCode();
                if (this.PrdCode != null)
                    hashCode = hashCode * 59 + this.PrdCode.GetHashCode();
                if (this.PrdCodeExternal != null)
                    hashCode = hashCode * 59 + this.PrdCodeExternal.GetHashCode();
                if (this.PrdName != null)
                    hashCode = hashCode * 59 + this.PrdName.GetHashCode();
                if (this.PrdShortName != null)
                    hashCode = hashCode * 59 + this.PrdShortName.GetHashCode();
                if (this.PrdBrand != null)
                    hashCode = hashCode * 59 + this.PrdBrand.GetHashCode();
                if (this.PrdType != null)
                    hashCode = hashCode * 59 + this.PrdType.GetHashCode();
                if (this.PrdCountry != null)
                    hashCode = hashCode * 59 + this.PrdCountry.GetHashCode();
                if (this.Qty != null)
                    hashCode = hashCode * 59 + this.Qty.GetHashCode();
                if (this.IsExpDate != null)
                    hashCode = hashCode * 59 + this.IsExpDate.GetHashCode();
                if (this.ExpDate != null)
                    hashCode = hashCode * 59 + this.ExpDate.GetHashCode();
                if (this.IsLot != null)
                    hashCode = hashCode * 59 + this.IsLot.GetHashCode();
                if (this.Lot != null)
                    hashCode = hashCode * 59 + this.Lot.GetHashCode();
                if (this.Sscc != null)
                    hashCode = hashCode * 59 + this.Sscc.GetHashCode();
                if (this.IsContractPrice != null)
                    hashCode = hashCode * 59 + this.IsContractPrice.GetHashCode();
                if (this.Price != null)
                    hashCode = hashCode * 59 + this.Price.GetHashCode();
                if (this.SnType != null)
                    hashCode = hashCode * 59 + this.SnType.GetHashCode();
                if (this.Length != null)
                    hashCode = hashCode * 59 + this.Length.GetHashCode();
                if (this.Width != null)
                    hashCode = hashCode * 59 + this.Width.GetHashCode();
                if (this.Height != null)
                    hashCode = hashCode * 59 + this.Height.GetHashCode();
                if (this.Weight != null)
                    hashCode = hashCode * 59 + this.Weight.GetHashCode();
                if (this.ItemInBox != null)
                    hashCode = hashCode * 59 + this.ItemInBox.GetHashCode();
                if (this.Manufacturer != null)
                    hashCode = hashCode * 59 + this.Manufacturer.GetHashCode();
                if (this.Factory != null)
                    hashCode = hashCode * 59 + this.Factory.GetHashCode();
                if (this.Instruction != null)
                    hashCode = hashCode * 59 + this.Instruction.GetHashCode();
                if (this.Importer != null)
                    hashCode = hashCode * 59 + this.Importer.GetHashCode();
                if (this.Gender != null)
                    hashCode = hashCode * 59 + this.Gender.GetHashCode();
                if (this.Seller != null)
                    hashCode = hashCode * 59 + this.Seller.GetHashCode();
                if (this.Color != null)
                    hashCode = hashCode * 59 + this.Color.GetHashCode();
                if (this.Size != null)
                    hashCode = hashCode * 59 + this.Size.GetHashCode();
                if (this.Structure != null)
                    hashCode = hashCode * 59 + this.Structure.GetHashCode();
                if (this.IsNeedCheck != null)
                    hashCode = hashCode * 59 + this.IsNeedCheck.GetHashCode();
                if (this.PrdCategory != null)
                    hashCode = hashCode * 59 + this.PrdCategory.GetHashCode();
                if (this.PrdGroup != null)
                    hashCode = hashCode * 59 + this.PrdGroup.GetHashCode();
                if (this.CodeOnboxe != null)
                    hashCode = hashCode * 59 + this.CodeOnboxe.GetHashCode();
                if (this.AddInfo != null)
                    hashCode = hashCode * 59 + this.AddInfo.GetHashCode();
                if (this.MboxWidth != null)
                    hashCode = hashCode * 59 + this.MboxWidth.GetHashCode();
                if (this.MboxDepth != null)
                    hashCode = hashCode * 59 + this.MboxDepth.GetHashCode();
                if (this.MboxHeight != null)
                    hashCode = hashCode * 59 + this.MboxHeight.GetHashCode();
                if (this.MboxWeight != null)
                    hashCode = hashCode * 59 + this.MboxWeight.GetHashCode();
                if (this.BoxWidth != null)
                    hashCode = hashCode * 59 + this.BoxWidth.GetHashCode();
                if (this.BoxDepth != null)
                    hashCode = hashCode * 59 + this.BoxDepth.GetHashCode();
                if (this.BoxHeight != null)
                    hashCode = hashCode * 59 + this.BoxHeight.GetHashCode();
                if (this.BoxWeight != null)
                    hashCode = hashCode * 59 + this.BoxWeight.GetHashCode();
                if (this.ItemInMbox != null)
                    hashCode = hashCode * 59 + this.ItemInMbox.GetHashCode();
                if (this.P18 != null)
                    hashCode = hashCode * 59 + this.P18.GetHashCode();
                if (this.P22 != null)
                    hashCode = hashCode * 59 + this.P22.GetHashCode();
                if (this.Barcodes != null)
                    hashCode = hashCode * 59 + this.Barcodes.GetHashCode();
                if (this.AggregationCodes != null)
                    hashCode = hashCode * 59 + this.AggregationCodes.GetHashCode();
                if (this.SerialNumbers != null)
                    hashCode = hashCode * 59 + this.SerialNumbers.GetHashCode();
                return hashCode;
            }
        }
    }
}
