/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Агрегированный код
    /// </summary>
    [DataContract]
        public partial class ReceiptAggregationCodesDTO :  IEquatable<ReceiptAggregationCodesDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceiptAggregationCodesDTO" /> class.
        /// </summary>
        /// <param name="sscc">Код (required).</param>
        /// <param name="serialNumbers">Маркировка.</param>
        public ReceiptAggregationCodesDTO(string sscc = default(string), List<string> serialNumbers = default(List<string>))
        {
            // to ensure "sscc" is required (not null)
            if (sscc == null)
            {
                throw new InvalidDataException("sscc is a required property for ReceiptAggregationCodesDTO and cannot be null");
            }
            else
            {
                this.Sscc = sscc;
            }
            this.SerialNumbers = serialNumbers;
        }
        
        /// <summary>
        /// Код
        /// </summary>
        /// <value>Код</value>
        [DataMember(Name="sscc", EmitDefaultValue=false)]
        public string Sscc { get; set; }

        /// <summary>
        /// Маркировка
        /// </summary>
        /// <value>Маркировка</value>
        [DataMember(Name="serialNumbers", EmitDefaultValue=false)]
        public List<string> SerialNumbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReceiptAggregationCodesDTO {\n");
            sb.Append("  Sscc: ").Append(Sscc).Append("\n");
            sb.Append("  SerialNumbers: ").Append(SerialNumbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReceiptAggregationCodesDTO);
        }

        /// <summary>
        /// Returns true if ReceiptAggregationCodesDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceiptAggregationCodesDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceiptAggregationCodesDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Sscc == input.Sscc ||
                    (this.Sscc != null &&
                    this.Sscc.Equals(input.Sscc))
                ) && 
                (
                    this.SerialNumbers == input.SerialNumbers ||
                    this.SerialNumbers != null &&
                    input.SerialNumbers != null &&
                    this.SerialNumbers.SequenceEqual(input.SerialNumbers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Sscc != null)
                    hashCode = hashCode * 59 + this.Sscc.GetHashCode();
                if (this.SerialNumbers != null)
                    hashCode = hashCode * 59 + this.SerialNumbers.GetHashCode();
                return hashCode;
            }
        }
    }
}
