/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// ReceiptStatusDTO
    /// </summary>
    [DataContract]
        public partial class ReceiptStatusDTO :  IEquatable<ReceiptStatusDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceiptStatusDTO" /> class.
        /// </summary>
        /// <param name="code">Код (required).</param>
        /// <param name="externalID">Внешний идентификатор поставки.</param>
        /// <param name="depCode">Код клиента (required).</param>
        /// <param name="warehouseCode">Код склада (required).</param>
        /// <param name="eventStatus">Статус (required).</param>
        /// <param name="eventDate">Дата изменения статуса (required).</param>
        /// <param name="items">Строки поставки (required).</param>
        /// <param name="serialNumbers">Маркировка.</param>
        public ReceiptStatusDTO(string code = default(string), string externalID = default(string), string depCode = default(string), string warehouseCode = default(string), string eventStatus = default(string), DateTime? eventDate = default(DateTime?), List<ReceiptStatusItemDTO> items = default(List<ReceiptStatusItemDTO>), List<SerialNumberDTO> serialNumbers = default(List<SerialNumberDTO>))
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new InvalidDataException("code is a required property for ReceiptStatusDTO and cannot be null");
            }
            else
            {
                this.Code = code;
            }
            // to ensure "depCode" is required (not null)
            if (depCode == null)
            {
                throw new InvalidDataException("depCode is a required property for ReceiptStatusDTO and cannot be null");
            }
            else
            {
                this.DepCode = depCode;
            }
            // to ensure "warehouseCode" is required (not null)
            if (warehouseCode == null)
            {
                throw new InvalidDataException("warehouseCode is a required property for ReceiptStatusDTO and cannot be null");
            }
            else
            {
                this.WarehouseCode = warehouseCode;
            }
            // to ensure "eventStatus" is required (not null)
            if (eventStatus == null)
            {
                throw new InvalidDataException("eventStatus is a required property for ReceiptStatusDTO and cannot be null");
            }
            else
            {
                this.EventStatus = eventStatus;
            }
            // to ensure "eventDate" is required (not null)
            if (eventDate == null)
            {
                throw new InvalidDataException("eventDate is a required property for ReceiptStatusDTO and cannot be null");
            }
            else
            {
                this.EventDate = eventDate;
            }
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new InvalidDataException("items is a required property for ReceiptStatusDTO and cannot be null");
            }
            else
            {
                this.Items = items;
            }
            this.ExternalID = externalID;
            this.SerialNumbers = serialNumbers;
        }
        
        /// <summary>
        /// Код
        /// </summary>
        /// <value>Код</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Внешний идентификатор поставки
        /// </summary>
        /// <value>Внешний идентификатор поставки</value>
        [DataMember(Name="externalID", EmitDefaultValue=false)]
        public string ExternalID { get; set; }

        /// <summary>
        /// Код клиента
        /// </summary>
        /// <value>Код клиента</value>
        [DataMember(Name="depCode", EmitDefaultValue=false)]
        public string DepCode { get; set; }

        /// <summary>
        /// Код склада
        /// </summary>
        /// <value>Код склада</value>
        [DataMember(Name="warehouseCode", EmitDefaultValue=false)]
        public string WarehouseCode { get; set; }

        /// <summary>
        /// Статус
        /// </summary>
        /// <value>Статус</value>
        [DataMember(Name="eventStatus", EmitDefaultValue=false)]
        public string EventStatus { get; set; }

        /// <summary>
        /// Дата изменения статуса
        /// </summary>
        /// <value>Дата изменения статуса</value>
        [DataMember(Name="eventDate", EmitDefaultValue=false)]
        public DateTime? EventDate { get; set; }

        /// <summary>
        /// Строки поставки
        /// </summary>
        /// <value>Строки поставки</value>
        [DataMember(Name="items", EmitDefaultValue=false)]
        public List<ReceiptStatusItemDTO> Items { get; set; }

        /// <summary>
        /// Маркировка
        /// </summary>
        /// <value>Маркировка</value>
        [DataMember(Name="serialNumbers", EmitDefaultValue=false)]
        public List<SerialNumberDTO> SerialNumbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReceiptStatusDTO {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  ExternalID: ").Append(ExternalID).Append("\n");
            sb.Append("  DepCode: ").Append(DepCode).Append("\n");
            sb.Append("  WarehouseCode: ").Append(WarehouseCode).Append("\n");
            sb.Append("  EventStatus: ").Append(EventStatus).Append("\n");
            sb.Append("  EventDate: ").Append(EventDate).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  SerialNumbers: ").Append(SerialNumbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReceiptStatusDTO);
        }

        /// <summary>
        /// Returns true if ReceiptStatusDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceiptStatusDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceiptStatusDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.ExternalID == input.ExternalID ||
                    (this.ExternalID != null &&
                    this.ExternalID.Equals(input.ExternalID))
                ) && 
                (
                    this.DepCode == input.DepCode ||
                    (this.DepCode != null &&
                    this.DepCode.Equals(input.DepCode))
                ) && 
                (
                    this.WarehouseCode == input.WarehouseCode ||
                    (this.WarehouseCode != null &&
                    this.WarehouseCode.Equals(input.WarehouseCode))
                ) && 
                (
                    this.EventStatus == input.EventStatus ||
                    (this.EventStatus != null &&
                    this.EventStatus.Equals(input.EventStatus))
                ) && 
                (
                    this.EventDate == input.EventDate ||
                    (this.EventDate != null &&
                    this.EventDate.Equals(input.EventDate))
                ) && 
                (
                    this.Items == input.Items ||
                    this.Items != null &&
                    input.Items != null &&
                    this.Items.SequenceEqual(input.Items)
                ) && 
                (
                    this.SerialNumbers == input.SerialNumbers ||
                    this.SerialNumbers != null &&
                    input.SerialNumbers != null &&
                    this.SerialNumbers.SequenceEqual(input.SerialNumbers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.ExternalID != null)
                    hashCode = hashCode * 59 + this.ExternalID.GetHashCode();
                if (this.DepCode != null)
                    hashCode = hashCode * 59 + this.DepCode.GetHashCode();
                if (this.WarehouseCode != null)
                    hashCode = hashCode * 59 + this.WarehouseCode.GetHashCode();
                if (this.EventStatus != null)
                    hashCode = hashCode * 59 + this.EventStatus.GetHashCode();
                if (this.EventDate != null)
                    hashCode = hashCode * 59 + this.EventDate.GetHashCode();
                if (this.Items != null)
                    hashCode = hashCode * 59 + this.Items.GetHashCode();
                if (this.SerialNumbers != null)
                    hashCode = hashCode * 59 + this.SerialNumbers.GetHashCode();
                return hashCode;
            }
        }
    }
}
