/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Класс cтрок поставки маркировки
    /// </summary>
    [DataContract]
        public partial class ReceiptSerialNumbersItemDTO :  IEquatable<ReceiptSerialNumbersItemDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReceiptSerialNumbersItemDTO" /> class.
        /// </summary>
        /// <param name="prdCode">Артикул (required).</param>
        /// <param name="aggregationCodes">Агрегированные коды маркировки.</param>
        /// <param name="serialNumbers">Маркировка (required).</param>
        public ReceiptSerialNumbersItemDTO(string prdCode = default(string), List<ReceiptAggregationCodesDTO> aggregationCodes = default(List<ReceiptAggregationCodesDTO>), List<string> serialNumbers = default(List<string>))
        {
            // to ensure "prdCode" is required (not null)
            if (prdCode == null)
            {
                throw new InvalidDataException("prdCode is a required property for ReceiptSerialNumbersItemDTO and cannot be null");
            }
            else
            {
                this.PrdCode = prdCode;
            }
            // to ensure "serialNumbers" is required (not null)
            if (serialNumbers == null)
            {
                throw new InvalidDataException("serialNumbers is a required property for ReceiptSerialNumbersItemDTO and cannot be null");
            }
            else
            {
                this.SerialNumbers = serialNumbers;
            }
            this.AggregationCodes = aggregationCodes;
        }
        
        /// <summary>
        /// Артикул
        /// </summary>
        /// <value>Артикул</value>
        [DataMember(Name="prdCode", EmitDefaultValue=false)]
        public string PrdCode { get; set; }

        /// <summary>
        /// Агрегированные коды маркировки
        /// </summary>
        /// <value>Агрегированные коды маркировки</value>
        [DataMember(Name="aggregationCodes", EmitDefaultValue=false)]
        public List<ReceiptAggregationCodesDTO> AggregationCodes { get; set; }

        /// <summary>
        /// Маркировка
        /// </summary>
        /// <value>Маркировка</value>
        [DataMember(Name="serialNumbers", EmitDefaultValue=false)]
        public List<string> SerialNumbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReceiptSerialNumbersItemDTO {\n");
            sb.Append("  PrdCode: ").Append(PrdCode).Append("\n");
            sb.Append("  AggregationCodes: ").Append(AggregationCodes).Append("\n");
            sb.Append("  SerialNumbers: ").Append(SerialNumbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReceiptSerialNumbersItemDTO);
        }

        /// <summary>
        /// Returns true if ReceiptSerialNumbersItemDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceiptSerialNumbersItemDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceiptSerialNumbersItemDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PrdCode == input.PrdCode ||
                    (this.PrdCode != null &&
                    this.PrdCode.Equals(input.PrdCode))
                ) && 
                (
                    this.AggregationCodes == input.AggregationCodes ||
                    this.AggregationCodes != null &&
                    input.AggregationCodes != null &&
                    this.AggregationCodes.SequenceEqual(input.AggregationCodes)
                ) && 
                (
                    this.SerialNumbers == input.SerialNumbers ||
                    this.SerialNumbers != null &&
                    input.SerialNumbers != null &&
                    this.SerialNumbers.SequenceEqual(input.SerialNumbers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PrdCode != null)
                    hashCode = hashCode * 59 + this.PrdCode.GetHashCode();
                if (this.AggregationCodes != null)
                    hashCode = hashCode * 59 + this.AggregationCodes.GetHashCode();
                if (this.SerialNumbers != null)
                    hashCode = hashCode * 59 + this.SerialNumbers.GetHashCode();
                return hashCode;
            }
        }
    }
}
