/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Маркировка \&quot;Честный знак\&quot;
    /// </summary>
    [DataContract]
        public partial class SerialNumberDTO :  IEquatable<SerialNumberDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SerialNumberDTO" /> class.
        /// </summary>
        /// <param name="prdCode">Артикул (required).</param>
        /// <param name="prdCodeExternal">Артикул клиентский.</param>
        /// <param name="serialNumber">Код первые 31 символов (required).</param>
        /// <param name="serialNumberFull">Исходный код (required).</param>
        public SerialNumberDTO(string prdCode = default(string), string prdCodeExternal = default(string), string serialNumber = default(string), string serialNumberFull = default(string))
        {
            // to ensure "prdCode" is required (not null)
            if (prdCode == null)
            {
                throw new InvalidDataException("prdCode is a required property for SerialNumberDTO and cannot be null");
            }
            else
            {
                this.PrdCode = prdCode;
            }
            // to ensure "serialNumber" is required (not null)
            if (serialNumber == null)
            {
                throw new InvalidDataException("serialNumber is a required property for SerialNumberDTO and cannot be null");
            }
            else
            {
                this.SerialNumber = serialNumber;
            }
            // to ensure "serialNumberFull" is required (not null)
            if (serialNumberFull == null)
            {
                throw new InvalidDataException("serialNumberFull is a required property for SerialNumberDTO and cannot be null");
            }
            else
            {
                this.SerialNumberFull = serialNumberFull;
            }
            this.PrdCodeExternal = prdCodeExternal;
        }
        
        /// <summary>
        /// Артикул
        /// </summary>
        /// <value>Артикул</value>
        [DataMember(Name="prdCode", EmitDefaultValue=false)]
        public string PrdCode { get; set; }

        /// <summary>
        /// Артикул клиентский
        /// </summary>
        /// <value>Артикул клиентский</value>
        [DataMember(Name="prdCodeExternal", EmitDefaultValue=false)]
        public string PrdCodeExternal { get; set; }

        /// <summary>
        /// Код первые 31 символов
        /// </summary>
        /// <value>Код первые 31 символов</value>
        [DataMember(Name="serialNumber", EmitDefaultValue=false)]
        public string SerialNumber { get; set; }

        /// <summary>
        /// Исходный код
        /// </summary>
        /// <value>Исходный код</value>
        [DataMember(Name="serialNumberFull", EmitDefaultValue=false)]
        public string SerialNumberFull { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SerialNumberDTO {\n");
            sb.Append("  PrdCode: ").Append(PrdCode).Append("\n");
            sb.Append("  PrdCodeExternal: ").Append(PrdCodeExternal).Append("\n");
            sb.Append("  SerialNumber: ").Append(SerialNumber).Append("\n");
            sb.Append("  SerialNumberFull: ").Append(SerialNumberFull).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SerialNumberDTO);
        }

        /// <summary>
        /// Returns true if SerialNumberDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of SerialNumberDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SerialNumberDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PrdCode == input.PrdCode ||
                    (this.PrdCode != null &&
                    this.PrdCode.Equals(input.PrdCode))
                ) && 
                (
                    this.PrdCodeExternal == input.PrdCodeExternal ||
                    (this.PrdCodeExternal != null &&
                    this.PrdCodeExternal.Equals(input.PrdCodeExternal))
                ) && 
                (
                    this.SerialNumber == input.SerialNumber ||
                    (this.SerialNumber != null &&
                    this.SerialNumber.Equals(input.SerialNumber))
                ) && 
                (
                    this.SerialNumberFull == input.SerialNumberFull ||
                    (this.SerialNumberFull != null &&
                    this.SerialNumberFull.Equals(input.SerialNumberFull))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PrdCode != null)
                    hashCode = hashCode * 59 + this.PrdCode.GetHashCode();
                if (this.PrdCodeExternal != null)
                    hashCode = hashCode * 59 + this.PrdCodeExternal.GetHashCode();
                if (this.SerialNumber != null)
                    hashCode = hashCode * 59 + this.SerialNumber.GetHashCode();
                if (this.SerialNumberFull != null)
                    hashCode = hashCode * 59 + this.SerialNumberFull.GetHashCode();
                return hashCode;
            }
        }
    }
}
