/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Доступные склады
    /// </summary>
    [DataContract]
        public partial class WareHouseResponse :  IEquatable<WareHouseResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WareHouseResponse" /> class.
        /// </summary>
        /// <param name="isSuccess">true - истина, false - ошибка (required).</param>
        /// <param name="message">Сообщение ошибки (required).</param>
        /// <param name="operationObject">Данные (required).</param>
        public WareHouseResponse(bool? isSuccess = default(bool?), string message = default(string), List<WareHouseDTO> operationObject = default(List<WareHouseDTO>))
        {
            // to ensure "isSuccess" is required (not null)
            if (isSuccess == null)
            {
                throw new InvalidDataException("isSuccess is a required property for WareHouseResponse and cannot be null");
            }
            else
            {
                this.IsSuccess = isSuccess;
            }
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new InvalidDataException("message is a required property for WareHouseResponse and cannot be null");
            }
            else
            {
                this.Message = message;
            }
            // to ensure "operationObject" is required (not null)
            if (operationObject == null)
            {
                throw new InvalidDataException("operationObject is a required property for WareHouseResponse and cannot be null");
            }
            else
            {
                this.OperationObject = operationObject;
            }
        }
        
        /// <summary>
        /// true - истина, false - ошибка
        /// </summary>
        /// <value>true - истина, false - ошибка</value>
        [DataMember(Name="isSuccess", EmitDefaultValue=false)]
        public bool? IsSuccess { get; set; }

        /// <summary>
        /// Сообщение ошибки
        /// </summary>
        /// <value>Сообщение ошибки</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Данные
        /// </summary>
        /// <value>Данные</value>
        [DataMember(Name="operationObject", EmitDefaultValue=false)]
        public List<WareHouseDTO> OperationObject { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WareHouseResponse {\n");
            sb.Append("  IsSuccess: ").Append(IsSuccess).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  OperationObject: ").Append(OperationObject).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WareHouseResponse);
        }

        /// <summary>
        /// Returns true if WareHouseResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of WareHouseResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WareHouseResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsSuccess == input.IsSuccess ||
                    (this.IsSuccess != null &&
                    this.IsSuccess.Equals(input.IsSuccess))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.OperationObject == input.OperationObject ||
                    this.OperationObject != null &&
                    input.OperationObject != null &&
                    this.OperationObject.SequenceEqual(input.OperationObject)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsSuccess != null)
                    hashCode = hashCode * 59 + this.IsSuccess.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.OperationObject != null)
                    hashCode = hashCode * 59 + this.OperationObject.GetHashCode();
                return hashCode;
            }
        }
    }
}
