/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Класс строки заказа
    /// </summary>
    [DataContract]
        public partial class OrderItemDTO :  IEquatable<OrderItemDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderItemDTO" /> class.
        /// </summary>
        /// <param name="number">Номер строки.</param>
        /// <param name="prdCode">Артикул (required).</param>
        /// <param name="qty">Количество (required).</param>
        /// <param name="qtyShipPacking">Количество в отгрузочной упаковке.</param>
        /// <param name="quality">Качество (required).</param>
        /// <param name="expDate">Дата окончания срока годности.</param>
        /// <param name="lot">Партия.</param>
        /// <param name="sscc">Код контейнера.</param>
        /// <param name="multiplicity">Кратность.</param>
        /// <param name="price">Цена в рублях.</param>
        public OrderItemDTO()
        {
        }
        
        /// <summary>
        /// Номер строки
        /// </summary>
        /// <value>Номер строки</value>
        [DataMember(Name="number", EmitDefaultValue=false)]
        public string Number { get; set; }

        /// <summary>
        /// Артикул
        /// </summary>
        /// <value>Артикул</value>
        [DataMember(Name="prdCode", EmitDefaultValue=false)]
        public string PrdCode { get; set; }

        /// <summary>
        /// Количество
        /// </summary>
        /// <value>Количество</value>
        [DataMember(Name="qty", EmitDefaultValue=false)]
        public int? Qty { get; set; }

        /// <summary>
        /// Количество в отгрузочной упаковке
        /// </summary>
        /// <value>Количество в отгрузочной упаковке</value>
        [DataMember(Name="qtyShipPacking", EmitDefaultValue=false)]
        public int? QtyShipPacking { get; set; }

        /// <summary>
        /// Качество
        /// </summary>
        /// <value>Качество</value>
        [DataMember(Name="quality", EmitDefaultValue=false)]
        public string Quality { get; set; }

        /// <summary>
        /// Дата окончания срока годности
        /// </summary>
        /// <value>Дата окончания срока годности</value>
        [DataMember(Name="expDate", EmitDefaultValue=false)]
        public DateTime? ExpDate { get; set; }

        /// <summary>
        /// Партия
        /// </summary>
        /// <value>Партия</value>
        [DataMember(Name="lot", EmitDefaultValue=false)]
        public string Lot { get; set; }

        /// <summary>
        /// Код контейнера
        /// </summary>
        /// <value>Код контейнера</value>
        [DataMember(Name="sscc", EmitDefaultValue=false)]
        public string Sscc { get; set; }

        /// <summary>
        /// Кратность
        /// </summary>
        /// <value>Кратность</value>
        [DataMember(Name="multiplicity", EmitDefaultValue=false)]
        public int? Multiplicity { get; set; }

        /// <summary>
        /// Цена в рублях
        /// </summary>
        /// <value>Цена в рублях</value>
        [DataMember(Name="price", EmitDefaultValue=false)]
        public float? Price { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderItemDTO {\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  PrdCode: ").Append(PrdCode).Append("\n");
            sb.Append("  Qty: ").Append(Qty).Append("\n");
            sb.Append("  QtyShipPacking: ").Append(QtyShipPacking).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  ExpDate: ").Append(ExpDate).Append("\n");
            sb.Append("  Lot: ").Append(Lot).Append("\n");
            sb.Append("  Sscc: ").Append(Sscc).Append("\n");
            sb.Append("  Multiplicity: ").Append(Multiplicity).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrderItemDTO);
        }

        /// <summary>
        /// Returns true if OrderItemDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of OrderItemDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderItemDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Number == input.Number ||
                    (this.Number != null &&
                    this.Number.Equals(input.Number))
                ) && 
                (
                    this.PrdCode == input.PrdCode ||
                    (this.PrdCode != null &&
                    this.PrdCode.Equals(input.PrdCode))
                ) && 
                (
                    this.Qty == input.Qty ||
                    (this.Qty != null &&
                    this.Qty.Equals(input.Qty))
                ) && 
                (
                    this.QtyShipPacking == input.QtyShipPacking ||
                    (this.QtyShipPacking != null &&
                    this.QtyShipPacking.Equals(input.QtyShipPacking))
                ) && 
                (
                    this.Quality == input.Quality ||
                    (this.Quality != null &&
                    this.Quality.Equals(input.Quality))
                ) && 
                (
                    this.ExpDate == input.ExpDate ||
                    (this.ExpDate != null &&
                    this.ExpDate.Equals(input.ExpDate))
                ) && 
                (
                    this.Lot == input.Lot ||
                    (this.Lot != null &&
                    this.Lot.Equals(input.Lot))
                ) && 
                (
                    this.Sscc == input.Sscc ||
                    (this.Sscc != null &&
                    this.Sscc.Equals(input.Sscc))
                ) && 
                (
                    this.Multiplicity == input.Multiplicity ||
                    (this.Multiplicity != null &&
                    this.Multiplicity.Equals(input.Multiplicity))
                ) && 
                (
                    this.Price == input.Price ||
                    (this.Price != null &&
                    this.Price.Equals(input.Price))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Number != null)
                    hashCode = hashCode * 59 + this.Number.GetHashCode();
                if (this.PrdCode != null)
                    hashCode = hashCode * 59 + this.PrdCode.GetHashCode();
                if (this.Qty != null)
                    hashCode = hashCode * 59 + this.Qty.GetHashCode();
                if (this.QtyShipPacking != null)
                    hashCode = hashCode * 59 + this.QtyShipPacking.GetHashCode();
                if (this.Quality != null)
                    hashCode = hashCode * 59 + this.Quality.GetHashCode();
                if (this.ExpDate != null)
                    hashCode = hashCode * 59 + this.ExpDate.GetHashCode();
                if (this.Lot != null)
                    hashCode = hashCode * 59 + this.Lot.GetHashCode();
                if (this.Sscc != null)
                    hashCode = hashCode * 59 + this.Sscc.GetHashCode();
                if (this.Multiplicity != null)
                    hashCode = hashCode * 59 + this.Multiplicity.GetHashCode();
                if (this.Price != null)
                    hashCode = hashCode * 59 + this.Price.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
