/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// OrderStatusResponse
    /// </summary>
    [DataContract]
        public partial class OrderStatusResponse :  IEquatable<OrderStatusResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderStatusResponse" /> class.
        /// </summary>
        /// <param name="isSuccess">true - истина, false - ошибка (required).</param>
        /// <param name="message">Сообщение ошибки (required).</param>
        /// <param name="operationObject">operationObject (required).</param>
        public OrderStatusResponse(bool? isSuccess = default(bool?), string message = default(string), OrderStatusDTO operationObject = default(OrderStatusDTO))
        {
            // to ensure "isSuccess" is required (not null)
            if (isSuccess == null)
            {
                throw new InvalidDataException("isSuccess is a required property for OrderStatusResponse and cannot be null");
            }
            else
            {
                this.IsSuccess = isSuccess;
            }
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new InvalidDataException("message is a required property for OrderStatusResponse and cannot be null");
            }
            else
            {
                this.Message = message;
            }
            // to ensure "operationObject" is required (not null)
            if (operationObject == null)
            {
                throw new InvalidDataException("operationObject is a required property for OrderStatusResponse and cannot be null");
            }
            else
            {
                this.OperationObject = operationObject;
            }
        }
        
        /// <summary>
        /// true - истина, false - ошибка
        /// </summary>
        /// <value>true - истина, false - ошибка</value>
        [DataMember(Name="isSuccess", EmitDefaultValue=false)]
        public bool? IsSuccess { get; set; }

        /// <summary>
        /// Сообщение ошибки
        /// </summary>
        /// <value>Сообщение ошибки</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets OperationObject
        /// </summary>
        [DataMember(Name="operationObject", EmitDefaultValue=false)]
        public OrderStatusDTO OperationObject { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderStatusResponse {\n");
            sb.Append("  IsSuccess: ").Append(IsSuccess).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  OperationObject: ").Append(OperationObject).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrderStatusResponse);
        }

        /// <summary>
        /// Returns true if OrderStatusResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of OrderStatusResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderStatusResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsSuccess == input.IsSuccess ||
                    (this.IsSuccess != null &&
                    this.IsSuccess.Equals(input.IsSuccess))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.OperationObject == input.OperationObject ||
                    (this.OperationObject != null &&
                    this.OperationObject.Equals(input.OperationObject))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsSuccess != null)
                    hashCode = hashCode * 59 + this.IsSuccess.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.OperationObject != null)
                    hashCode = hashCode * 59 + this.OperationObject.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
