/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Запрос создания заказа
    /// </summary>
    [DataContract]
        public partial class OrderRequest :  IEquatable<OrderRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderRequest" /> class.
        /// </summary>
        /// <param name="code">Код заказа (required).</param>
        /// <param name="receiptCode">Код прихода к которому относиться  заказ.</param>
        /// <param name="externalID">Внешний идентификатор заказа.</param>
        /// <param name="externalCode">Внешний код заказа.</param>
        /// <param name="depCode">Код клиента (required).</param>
        /// <param name="warehouseCode">Код склада (required).</param>
        /// <param name="marketplaceCode">Код маркетплейса.</param>
        /// <param name="priority">Приоритет заказа (required).</param>
        /// <param name="type">Тип обработки заказа (required).</param>
        /// <param name="packType">Тип сборки (упаковки).</param>
        /// <param name="shipType">Тип отгрузки.</param>
        /// <param name="clientCode">Код контрагента (required).</param>
        /// <param name="clientName">Наименование контрагента (required).</param>
        /// <param name="clientAdress">Адрес контрагента.</param>
        /// <param name="sender">Грузоотправитель.</param>
        /// <param name="deliveryCode">Код перевозчика или направления доставки.</param>
        /// <param name="deliveryAdress">Адрес доставки (required).</param>
        /// <param name="expExecuteDate">Ожидаемая дата упаковки.</param>
        /// <param name="expDate">Ожидаемая дата отгрузки (required).</param>
        /// <param name="expDeliveryDate">Ожидаемая дата доставки.</param>
        /// <param name="isEDO">Необходима ли печать документов (required).</param>
        /// <param name="description">Примечание/Описание.</param>
        /// <param name="items">Строки заказа (required).</param>
        public OrderRequest()
        {           
        }
        
        /// <summary>
        /// Код заказа
        /// </summary>
        /// <value>Код заказа</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Код прихода к которому относиться  заказ
        /// </summary>
        /// <value>Код прихода к которому относиться  заказ</value>
        [DataMember(Name="receiptCode", EmitDefaultValue=false)]
        public string ReceiptCode { get; set; }

        /// <summary>
        /// Внешний идентификатор заказа
        /// </summary>
        /// <value>Внешний идентификатор заказа</value>
        [DataMember(Name="externalID", EmitDefaultValue=false)]
        public string ExternalID { get; set; }

        /// <summary>
        /// Внешний код заказа
        /// </summary>
        /// <value>Внешний код заказа</value>
        [DataMember(Name="externalCode", EmitDefaultValue=false)]
        public string ExternalCode { get; set; }

        /// <summary>
        /// Код клиента
        /// </summary>
        /// <value>Код клиента</value>
        [DataMember(Name="depCode", EmitDefaultValue=false)]
        public string DepCode { get; set; }

        /// <summary>
        /// Код склада
        /// </summary>
        /// <value>Код склада</value>
        [DataMember(Name="warehouseCode", EmitDefaultValue=false)]
        public string WarehouseCode { get; set; }

        /// <summary>
        /// Код маркетплейса
        /// </summary>
        /// <value>Код маркетплейса</value>
        [DataMember(Name="marketplaceCode", EmitDefaultValue=false)]
        public string MarketplaceCode { get; set; }

        /// <summary>
        /// Приоритет заказа
        /// </summary>
        /// <value>Приоритет заказа</value>
        [DataMember(Name="priority", EmitDefaultValue=false)]
        public string Priority { get; set; }

        /// <summary>
        /// Тип обработки заказа
        /// </summary>
        /// <value>Тип обработки заказа</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Тип сборки (упаковки)
        /// </summary>
        /// <value>Тип сборки (упаковки)</value>
        [DataMember(Name="packType", EmitDefaultValue=false)]
        public string PackType { get; set; }

        /// <summary>
        /// Тип отгрузки
        /// </summary>
        /// <value>Тип отгрузки</value>
        [DataMember(Name="shipType", EmitDefaultValue=false)]
        public string ShipType { get; set; }

        /// <summary>
        /// Код контрагента
        /// </summary>
        /// <value>Код контрагента</value>
        [DataMember(Name="clientCode", EmitDefaultValue=false)]
        public string ClientCode { get; set; }

        /// <summary>
        /// Наименование контрагента
        /// </summary>
        /// <value>Наименование контрагента</value>
        [DataMember(Name="clientName", EmitDefaultValue=false)]
        public string ClientName { get; set; }

        /// <summary>
        /// Адрес контрагента
        /// </summary>
        /// <value>Адрес контрагента</value>
        [DataMember(Name="clientAdress", EmitDefaultValue=false)]
        public string ClientAdress { get; set; }

        /// <summary>
        /// Грузоотправитель
        /// </summary>
        /// <value>Грузоотправитель</value>
        [DataMember(Name="sender", EmitDefaultValue=false)]
        public string Sender { get; set; }

        /// <summary>
        /// Код перевозчика или направления доставки
        /// </summary>
        /// <value>Код перевозчика или направления доставки</value>
        [DataMember(Name="deliveryCode", EmitDefaultValue=false)]
        public string DeliveryCode { get; set; }

        /// <summary>
        /// Адрес доставки
        /// </summary>
        /// <value>Адрес доставки</value>
        [DataMember(Name="deliveryAdress", EmitDefaultValue=false)]
        public string DeliveryAdress { get; set; }

        /// <summary>
        /// Ожидаемая дата упаковки
        /// </summary>
        /// <value>Ожидаемая дата упаковки</value>
        [DataMember(Name="expExecuteDate", EmitDefaultValue=false)]
        public DateTime? ExpExecuteDate { get; set; }

        /// <summary>
        /// Ожидаемая дата отгрузки
        /// </summary>
        /// <value>Ожидаемая дата отгрузки</value>
        [DataMember(Name="expDate", EmitDefaultValue=false)]
        public DateTime? ExpDate { get; set; }

        /// <summary>
        /// Ожидаемая дата доставки
        /// </summary>
        /// <value>Ожидаемая дата доставки</value>
        [DataMember(Name="expDeliveryDate", EmitDefaultValue=false)]
        public DateTime? ExpDeliveryDate { get; set; }

        /// <summary>
        /// Необходима ли печать документов
        /// </summary>
        /// <value>Необходима ли печать документов</value>
        [DataMember(Name="isEDO", EmitDefaultValue=false)]
        public bool? IsEDO { get; set; }

        /// <summary>
        /// Примечание/Описание
        /// </summary>
        /// <value>Примечание/Описание</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Строки заказа
        /// </summary>
        /// <value>Строки заказа</value>
        [DataMember(Name="items", EmitDefaultValue=false)]
        public List<OrderItemDTO> Items { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderRequest {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  ReceiptCode: ").Append(ReceiptCode).Append("\n");
            sb.Append("  ExternalID: ").Append(ExternalID).Append("\n");
            sb.Append("  ExternalCode: ").Append(ExternalCode).Append("\n");
            sb.Append("  DepCode: ").Append(DepCode).Append("\n");
            sb.Append("  WarehouseCode: ").Append(WarehouseCode).Append("\n");
            sb.Append("  MarketplaceCode: ").Append(MarketplaceCode).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  PackType: ").Append(PackType).Append("\n");
            sb.Append("  ShipType: ").Append(ShipType).Append("\n");
            sb.Append("  ClientCode: ").Append(ClientCode).Append("\n");
            sb.Append("  ClientName: ").Append(ClientName).Append("\n");
            sb.Append("  ClientAdress: ").Append(ClientAdress).Append("\n");
            sb.Append("  Sender: ").Append(Sender).Append("\n");
            sb.Append("  DeliveryCode: ").Append(DeliveryCode).Append("\n");
            sb.Append("  DeliveryAdress: ").Append(DeliveryAdress).Append("\n");
            sb.Append("  ExpExecuteDate: ").Append(ExpExecuteDate).Append("\n");
            sb.Append("  ExpDate: ").Append(ExpDate).Append("\n");
            sb.Append("  ExpDeliveryDate: ").Append(ExpDeliveryDate).Append("\n");
            sb.Append("  IsEDO: ").Append(IsEDO).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrderRequest);
        }

        /// <summary>
        /// Returns true if OrderRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of OrderRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.ReceiptCode == input.ReceiptCode ||
                    (this.ReceiptCode != null &&
                    this.ReceiptCode.Equals(input.ReceiptCode))
                ) && 
                (
                    this.ExternalID == input.ExternalID ||
                    (this.ExternalID != null &&
                    this.ExternalID.Equals(input.ExternalID))
                ) && 
                (
                    this.ExternalCode == input.ExternalCode ||
                    (this.ExternalCode != null &&
                    this.ExternalCode.Equals(input.ExternalCode))
                ) && 
                (
                    this.DepCode == input.DepCode ||
                    (this.DepCode != null &&
                    this.DepCode.Equals(input.DepCode))
                ) && 
                (
                    this.WarehouseCode == input.WarehouseCode ||
                    (this.WarehouseCode != null &&
                    this.WarehouseCode.Equals(input.WarehouseCode))
                ) && 
                (
                    this.MarketplaceCode == input.MarketplaceCode ||
                    (this.MarketplaceCode != null &&
                    this.MarketplaceCode.Equals(input.MarketplaceCode))
                ) && 
                (
                    this.Priority == input.Priority ||
                    (this.Priority != null &&
                    this.Priority.Equals(input.Priority))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.PackType == input.PackType ||
                    (this.PackType != null &&
                    this.PackType.Equals(input.PackType))
                ) && 
                (
                    this.ShipType == input.ShipType ||
                    (this.ShipType != null &&
                    this.ShipType.Equals(input.ShipType))
                ) && 
                (
                    this.ClientCode == input.ClientCode ||
                    (this.ClientCode != null &&
                    this.ClientCode.Equals(input.ClientCode))
                ) && 
                (
                    this.ClientName == input.ClientName ||
                    (this.ClientName != null &&
                    this.ClientName.Equals(input.ClientName))
                ) && 
                (
                    this.ClientAdress == input.ClientAdress ||
                    (this.ClientAdress != null &&
                    this.ClientAdress.Equals(input.ClientAdress))
                ) && 
                (
                    this.Sender == input.Sender ||
                    (this.Sender != null &&
                    this.Sender.Equals(input.Sender))
                ) && 
                (
                    this.DeliveryCode == input.DeliveryCode ||
                    (this.DeliveryCode != null &&
                    this.DeliveryCode.Equals(input.DeliveryCode))
                ) && 
                (
                    this.DeliveryAdress == input.DeliveryAdress ||
                    (this.DeliveryAdress != null &&
                    this.DeliveryAdress.Equals(input.DeliveryAdress))
                ) && 
                (
                    this.ExpExecuteDate == input.ExpExecuteDate ||
                    (this.ExpExecuteDate != null &&
                    this.ExpExecuteDate.Equals(input.ExpExecuteDate))
                ) && 
                (
                    this.ExpDate == input.ExpDate ||
                    (this.ExpDate != null &&
                    this.ExpDate.Equals(input.ExpDate))
                ) && 
                (
                    this.ExpDeliveryDate == input.ExpDeliveryDate ||
                    (this.ExpDeliveryDate != null &&
                    this.ExpDeliveryDate.Equals(input.ExpDeliveryDate))
                ) && 
                (
                    this.IsEDO == input.IsEDO ||
                    (this.IsEDO != null &&
                    this.IsEDO.Equals(input.IsEDO))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Items == input.Items ||
                    this.Items != null &&
                    input.Items != null &&
                    this.Items.SequenceEqual(input.Items)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.ReceiptCode != null)
                    hashCode = hashCode * 59 + this.ReceiptCode.GetHashCode();
                if (this.ExternalID != null)
                    hashCode = hashCode * 59 + this.ExternalID.GetHashCode();
                if (this.ExternalCode != null)
                    hashCode = hashCode * 59 + this.ExternalCode.GetHashCode();
                if (this.DepCode != null)
                    hashCode = hashCode * 59 + this.DepCode.GetHashCode();
                if (this.WarehouseCode != null)
                    hashCode = hashCode * 59 + this.WarehouseCode.GetHashCode();
                if (this.MarketplaceCode != null)
                    hashCode = hashCode * 59 + this.MarketplaceCode.GetHashCode();
                if (this.Priority != null)
                    hashCode = hashCode * 59 + this.Priority.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.PackType != null)
                    hashCode = hashCode * 59 + this.PackType.GetHashCode();
                if (this.ShipType != null)
                    hashCode = hashCode * 59 + this.ShipType.GetHashCode();
                if (this.ClientCode != null)
                    hashCode = hashCode * 59 + this.ClientCode.GetHashCode();
                if (this.ClientName != null)
                    hashCode = hashCode * 59 + this.ClientName.GetHashCode();
                if (this.ClientAdress != null)
                    hashCode = hashCode * 59 + this.ClientAdress.GetHashCode();
                if (this.Sender != null)
                    hashCode = hashCode * 59 + this.Sender.GetHashCode();
                if (this.DeliveryCode != null)
                    hashCode = hashCode * 59 + this.DeliveryCode.GetHashCode();
                if (this.DeliveryAdress != null)
                    hashCode = hashCode * 59 + this.DeliveryAdress.GetHashCode();
                if (this.ExpExecuteDate != null)
                    hashCode = hashCode * 59 + this.ExpExecuteDate.GetHashCode();
                if (this.ExpDate != null)
                    hashCode = hashCode * 59 + this.ExpDate.GetHashCode();
                if (this.ExpDeliveryDate != null)
                    hashCode = hashCode * 59 + this.ExpDeliveryDate.GetHashCode();
                if (this.IsEDO != null)
                    hashCode = hashCode * 59 + this.IsEDO.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.Items != null)
                    hashCode = hashCode * 59 + this.Items.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
