/* 
 * WMS V7 REST API
 *
 * Техническая документация
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace NewNlsRemoteClient.Model
{
    /// <summary>
    /// Отмена документа
    /// </summary>
    [DataContract]
        public partial class DocumentCancelRequest :  IEquatable<DocumentCancelRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentCancelRequest" /> class.
        /// </summary>
        /// <param name="docType">Тип документа (required).</param>
        /// <param name="docCode">Код документа (required).</param>
        /// <param name="docExternalID">Внешний идентификатор документа.</param>
        /// <param name="depCode">Код клиента (required).</param>
        /// <param name="warehouseCode">Код склада (required).</param>
        public DocumentCancelRequest()
        {
        }
        
        /// <summary>
        /// Тип документа
        /// </summary>
        /// <value>Тип документа</value>
        [DataMember(Name="docType", EmitDefaultValue=false)]
        public string DocType { get; set; }

        /// <summary>
        /// Код документа
        /// </summary>
        /// <value>Код документа</value>
        [DataMember(Name="docCode", EmitDefaultValue=false)]
        public string DocCode { get; set; }

        /// <summary>
        /// Внешний идентификатор документа
        /// </summary>
        /// <value>Внешний идентификатор документа</value>
        [DataMember(Name="docExternalID", EmitDefaultValue=false)]
        public string DocExternalID { get; set; }

        /// <summary>
        /// Код клиента
        /// </summary>
        /// <value>Код клиента</value>
        [DataMember(Name="depCode", EmitDefaultValue=false)]
        public string DepCode { get; set; }

        /// <summary>
        /// Код склада
        /// </summary>
        /// <value>Код склада</value>
        [DataMember(Name="warehouseCode", EmitDefaultValue=false)]
        public string WarehouseCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentCancelRequest {\n");
            sb.Append("  DocType: ").Append(DocType).Append("\n");
            sb.Append("  DocCode: ").Append(DocCode).Append("\n");
            sb.Append("  DocExternalID: ").Append(DocExternalID).Append("\n");
            sb.Append("  DepCode: ").Append(DepCode).Append("\n");
            sb.Append("  WarehouseCode: ").Append(WarehouseCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocumentCancelRequest);
        }

        /// <summary>
        /// Returns true if DocumentCancelRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of DocumentCancelRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentCancelRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DocType == input.DocType ||
                    (this.DocType != null &&
                    this.DocType.Equals(input.DocType))
                ) && 
                (
                    this.DocCode == input.DocCode ||
                    (this.DocCode != null &&
                    this.DocCode.Equals(input.DocCode))
                ) && 
                (
                    this.DocExternalID == input.DocExternalID ||
                    (this.DocExternalID != null &&
                    this.DocExternalID.Equals(input.DocExternalID))
                ) && 
                (
                    this.DepCode == input.DepCode ||
                    (this.DepCode != null &&
                    this.DepCode.Equals(input.DepCode))
                ) && 
                (
                    this.WarehouseCode == input.WarehouseCode ||
                    (this.WarehouseCode != null &&
                    this.WarehouseCode.Equals(input.WarehouseCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DocType != null)
                    hashCode = hashCode * 59 + this.DocType.GetHashCode();
                if (this.DocCode != null)
                    hashCode = hashCode * 59 + this.DocCode.GetHashCode();
                if (this.DocExternalID != null)
                    hashCode = hashCode * 59 + this.DocExternalID.GetHashCode();
                if (this.DepCode != null)
                    hashCode = hashCode * 59 + this.DepCode.GetHashCode();
                if (this.WarehouseCode != null)
                    hashCode = hashCode * 59 + this.WarehouseCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
